---
title: "Analysis"
author: "Clare Clingain"
date: "April 22, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(lubridate)
require(dplyr)

# ferry data
#load("Data/Ferry/Clean/ferry_2018.RData")
# mta data
#load("Data/Clean/jan_clean.RData")
#load("Data/Clean/feb_clean.RData")
#load("Data/Clean/march_clean.RData")
#load("Data/Clean/april_clean.RData")
#load("Data/Clean/may_clean.RData")
#load("Data/Clean/june_clean.RData")
#load("Data/Clean/july_clean.RData")
#load("Data/Clean/aug_clean.RData")
```

# Merge and Unlist MTA data

```{r merge mta}
mta_master <- c(jan_clean, feb_clean, march_clean, april_clean, may_clean, june_clean, july_clean, aug_clean)

mta_master2 <- NULL

for(i in 56544:length(mta_master)){
  if(is.null(mta_master[[i]])==TRUE){
    print("This line is empty")
  } else{
  temp <- as.data.frame(as.matrix(mta_master[[i]]))
  mta_master2 <- rbind(mta_master2, temp)
  }
  print(i)
}

# fix classes
mta_master2$arrival_time <- parse_date_time(mta_master2$arrival_time,  "%Y-%m-%d %H:%M:%S")
# Save data
save(mta_master2, file = "Data/Clean/mta_master.RData")
```

# Check data

```{r}
head(mta_master2)
```


# Filter out holidays and weekends

```{r}
holidays <- c("2018-01-01","2018-01-15","2018-02-19","2018-05-28","2018-07-04")
weekends <- c("2018-01-06","2018-01-07","2018-01-13","2018-01-14","2018-01-20","2018-01-21","2018-01-27","2018-01-28","2018-02-03","2018-02-04","2018-02-10","2018-02-11","2018-02-17","2018-02-18","2018-02-24","2018-02-25","2018-03-03","2018-03-04","2018-03-10","2018-03-11","2018-03-17","2018-03-18","2018-03-24","2018-03-25","2018-03-31","2018-04-01","2018-04-07","2018-04-08","2018-04-14","2018-04-15","2018-04-21","2018-04-22","2018-04-28","2018-04-29","2018-05-05","2018-05-06","2018-05-12","2018-05-13","2018-05-19","2018-05-20","2018-05-26","2018-05-27","2018-06-02","2018-06-03","2018-06-09","2018-06-10","2018-06-16","2018-06-17","2018-06-23","2018-06-24","2018-06-30","2018-07-01","2018-07-07","2018-07-08","2018-07-14","2018-07-15","2018-07-21","2018-07-22","2018-07-28","2018-07-29","2018-08-04","2018-08-05","2018-08-11","2018-08-12","2018-08-18","2018-08-19","2018-08-25","2018-08-26")
# make time obects
holidays <- parse_date_time(holidays,"%Y-%m-%d")
weekends <- parse_date_time(weekends, "%Y-%m-%d")
# combine
holidays_weekends <- c(holidays,weekends)
# Filter
mta_sub <- filter(mta_master2, !grepl(paste(holidays_weekends, collapse="|"), arrival_time))

# Remove the 12/31 data
remove <- grep("2017-12-31", mta_sub$arrival_time)
mta_sub <- mta_sub[-remove,]

# remove the empty rows
mta_sub <- mta_sub[complete.cases(mta_sub[,"arrival_time"]),]

# remove empty ferry rows
ferry_sub <- ferry_master[complete.cases(ferry_master[,"time1"]),]
```


```{r}
# Find the row we should look in 
ferry_row <- unlist(lapply(mta_sub$arrival_time, FUN = function(x) max(which((as.Date(rownames(ferry_sub)) > x)==FALSE))))

# rename the rownames of mta_sub so that they'll match the ferry_row index
rownames(mta_sub) <- 1:dim(mta_sub)[1]
```


# Get closest ferry and wait times

```{r get ferry function}
get_ferry <- function(data, index_row){
  # Gets the wait time between ferry and train
  # data = MTA data frame 
  # index_row = ferry row that contains the train arrival time for each MTA row
  
  ## Step 1: Grab the closest ferry row
  row_index <- ferry_row[index_row]
  # include one row after for search 
  ferry_initial <- t(as.matrix(ferry_sub[row_index:(1+row_index),]))
  ferry_reshape <- c(ferry_initial[,1], ferry_initial[,2])
  ferry_dat <- as.POSIXct(ferry_reshape, "UTC")
  ## Step 2: Find the closest ferry
  closest_ferry_index <- min(which((ferry_dat - data$arrival_time[index_row])>0))

  closest_ferry <- ferry_dat[closest_ferry_index]

  # Return the closest ferry
  return(closest_ferry)
}

```

```{r run closest ferry}
# Initialize storage
ferry_match <- NULL

# Get the closest ferry for each arrival time
for (i in 1:dim(mta_sub)[1]){
  # printing i for time purposes
  print(i)
  
  ferry_match[i] <- get_ferry(mta_sub, i)
  
}
```


```{r}

get_wait <- function(data, ferry){
  ## Step 3: Obtain wait times
  data$wait_time <- as.numeric(data$closest_ferry - data$arrival_time)
  
  # if it looks like it's in minutes, change to seconds
  if(mean(data$wait_time)<120){
      data$wait_time <- data$wait_time*60
  } else {
    
  }

  ## Step 4: Obtain scheduled wait times
  data$wait_time_predicted <- as.numeric(data$ferry_departure - data$schedule)*60
  
  ## Step 5: Obtain scheduled closest ferries
  data$closest_ferry_predicted <- unlist(lapply(data$schedule, FUN = function(x) min(which((ferry_times - x)>0))))

  ## Step 6: Get the predicted ferry connections
  data$ferry_predicted <- unlist(lapply(data$closest_ferry, FUN = function(x)ferry_times[x]))

class(data$ferry_predicted) <- c('POSIXt', 'POSIXct')

return(data)
}
```

